version: '3.7'

networks:
  backend:
    driver: bridge

services:
  library:
    build:
      context: ./library
      dockerfile: Dockerfile
    volumes:
      - './library:/opt/library'
    ports:
      - '4000:4000'
    networks:
      - backend
    depends_on:
      - shield
  shield:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.sample
    ports:
      - '5000:5000'
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    image: 'postgres:11.10'
    environment:
      POSTGRES_USER: 'shield_library'
      POSTGRES_DB: 'shield_library'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - shield_library_postgres:/data/db
    networks:
      - backend
    ports:
      - 4321:5432

volumes:
  shield_library_postgres:
